### ISSUE TITLE
bug: failed to install on MAC OSX.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#199]
![image](https://user-images.githubusercontent.com/6814606/60643452-ae059e00-9e65-11e9-8603-dc549c597ebf.png)

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/60646884-0a20f000-9e6f-11e9-8b2a-8b89d814ad46.png)

**Comment by buhejiudewangxiansheng** [comment]
安装了automake和libtool，然后手动执行luarocks install apisix-*.rockspec --tree=deps --only-deps。
![image](https://user-images.githubusercontent.com/13926062/60702504-bfb47780-9f31-11e9-8e4c-6e15235c3355.png)

但是make dev，依然报错，Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.

**Comment by idevz** [comment]
This is not a apisix bug, but the error using about rapidjson installation with luarocks.
And you should try this:

* **first**: make sure you have lua5.1 installed (we must using lua5.1 to install luarocks, because of the rapidjson installed through luarock which install with lua5.3 is not compatible with luajit, but unfortunatly the `brew install lua` default install a lua5.3 not lua5.1)

* **second**: set a right LUA_LIBDIR for luarocks, you can run `luarocks config` to check your luarocks configs

**here are the commands**:

```bash```
\# run `brew list lua@5.1` to check if you have a lua5.1 installed
 ~/ brew list lua@5.1
/usr/local/Cellar/lua@5.1/5.1.5_8/bin/lua-5.1
/usr/local/Cellar/lua@5.1/5.1.5_8/bin/lua5.1
/usr/local/Cellar/lua@5.1/5.1.5_8/bin/luac-5.1
/usr/local/Cellar/lua@5.1/5.1.5_8/bin/luac5.1
/usr/local/Cellar/lua@5.1/5.1.5_8/include/lua-5.1/ (5 files)
/usr/local/Cellar/lua@5.1/5.1.5_8/lib/liblua.5.1.5.dylib
/usr/local/Cellar/lua@5.1/5.1.5_8/lib/pkgconfig/ (2 files)
/usr/local/Cellar/lua@5.1/5.1.5_8/lib/ (2 other files)
/usr/local/Cellar/lua@5.1/5.1.5_8/libexec/lib/pkgconfig/lua.pc
/usr/local/Cellar/lua@5.1/5.1.5_8/share/man/ (2 files)

\# to run `luarocks config variables.LUA_LIBDIR` set a right one for your luarocks
 ~/ luarocks config variables.LUA_LIBDIR /usr/local/Cellar/lua@5.1/5.1.5_8/lib
```

hope this works for you :)

**Comment by membphis** [comment]
>  ~/ luarocks config variables.LUA_LIBDIR /usr/local/Cellar/lua@5.1/5.1.5_8/lib

we'd better to use the luajit of OpenResty: `/usr/local/openresty/luajit/lib`

**Comment by moonming** [comment]
@idevz agreed. and we can use luarocks --scope to make sure change the variables in local not global.
```
OPTIONS
--scope=<scope>   The scope indicates which config file should be rewritten.
                   Accepted values are "system", "user" or "project".
                   * Using a wrapper created with `luarocks init`,
                     the default is "project".
                   * Using --local (or when `local_by_default` is `true`),
                     the default is "user".
                   * Otherwise, the default is "system".
```

**Comment by moonming** [comment]
fixed by https://github.com/iresty/apisix/commit/374aba472bce4fc08dd11d2da532463d28f4bb31
